import type { Database } from "@/types/database";

export const DEMO_USER_ID = "u1111111-1111-1111-1111-111111111111"; // Rohan Varma
export const MENTOR_RAHUL_ID = "u2222222-2222-2222-2222-222222222222"; // Rahul Sharma
export const MENTOR_ANANYA_ID = "u3333333-3333-3333-3333-333333333333"; // Ananya Patel
export const MENTOR_PRIYA_ID = "u4444444-4444-4444-4444-444444444444"; // Priya Nair
export const MENTOR_VIKRAM_ID = "u5555555-5555-5555-5555-555555555555"; // Vikram Rao

export const SEED_INSTITUTIONS: Database["public"]["Tables"]["institutions"]["Row"][] = [
  {
    id: "11111111-1111-1111-1111-111111111111",
    name: "ABC College of Engineering",
    short_name: "ABC CE",
    type: "college",
    location: "Chennai",
    country: "India",
    website: "https://abc-eng.edu",
    description: "Premier engineering college renowned for electronics and computing disciplines.",
    logo_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "22222222-2222-2222-2222-222222222222",
    name: "XYZ University of Technology",
    short_name: "XYZ Tech",
    type: "university",
    location: "Bangalore",
    country: "India",
    website: "https://xyz-tech.edu",
    description: "Research-driven university focused on artificial intelligence and cloud computing.",
    logo_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "33333333-3333-3333-3333-333333333333",
    name: "Global Institute of Science & Technology",
    short_name: "GIST",
    type: "institute",
    location: "Hyderabad",
    country: "India",
    website: "https://gist.edu",
    description: "Leading technical institute with extensive alumni across Fortune 500 tech companies.",
    logo_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SEED_USERS: Database["public"]["Tables"]["users"]["Row"][] = [
  {
    id: DEMO_USER_ID,
    email: "rohan.varma@student.abc.edu",
    full_name: "Rohan Varma",
    username: "rohan_v",
    profile_photo_url: null,
    headline: "ECE Senior Student @ ABC College | Aspiring Cloud Engineer",
    bio: "Passionate final-year student with strong electronics and programming fundamentals, actively transitioning into cloud infrastructure, containerization, and AWS architecture.",
    location: "Chennai",
    country: "India",
    phone: "+91 98765 43210",
    date_of_birth: "2004-05-14",
    created_at: "2026-01-10T10:00:00Z",
    updated_at: new Date().toISOString(),
    last_active_at: new Date().toISOString(),
    is_active: true,
    visibility: "public",
  },
  {
    id: MENTOR_RAHUL_ID,
    email: "rahul.sharma@aws.com",
    full_name: "Rahul Sharma",
    username: "rahul_cloud",
    profile_photo_url: null,
    headline: "Senior Cloud Architect @ AWS | ABC College ECE Alum ('21)",
    bio: "Transitioned from an ECE undergrad into cloud engineering. Now architecting resilient multi-region enterprise platforms at AWS. Dedicated mentor for students making the tech transition.",
    location: "Bangalore",
    country: "India",
    phone: null,
    date_of_birth: "1999-08-22",
    created_at: "2025-06-01T10:00:00Z",
    updated_at: new Date().toISOString(),
    last_active_at: new Date().toISOString(),
    is_active: true,
    visibility: "public",
  },
  {
    id: MENTOR_ANANYA_ID,
    email: "ananya.patel@microsoft.com",
    full_name: "Ananya Patel",
    username: "ananya_dev",
    profile_photo_url: null,
    headline: "Software Engineer II @ Microsoft | ABC College ECE Alum ('20)",
    bio: "ECE alumna who pivoted to large-scale backend systems. Mentors students on DSA, Java, Spring Boot, and technical interview strategies.",
    location: "Hyderabad",
    country: "India",
    phone: null,
    date_of_birth: "1998-11-04",
    created_at: "2025-05-12T10:00:00Z",
    updated_at: new Date().toISOString(),
    last_active_at: new Date().toISOString(),
    is_active: true,
    visibility: "public",
  },
  {
    id: MENTOR_PRIYA_ID,
    email: "priya.nair@google.com",
    full_name: "Priya Nair",
    username: "priya_sre",
    profile_photo_url: null,
    headline: "Site Reliability Engineer @ Google | XYZ Tech Alum ('22)",
    bio: "Passionate about Kubernetes reliability, observability, and infrastructure scaling. Regular speaker at cloud-native meetups.",
    location: "Bangalore",
    country: "India",
    phone: null,
    date_of_birth: "2000-03-18",
    created_at: "2025-07-20T10:00:00Z",
    updated_at: new Date().toISOString(),
    last_active_at: new Date().toISOString(),
    is_active: true,
    visibility: "public",
  },
  {
    id: MENTOR_VIKRAM_ID,
    email: "vikram.rao@cisco.com",
    full_name: "Vikram Rao",
    username: "vikram_sec",
    profile_photo_url: null,
    headline: "Cybersecurity Lead @ Cisco | Cloud Security & Threat Detection",
    bio: "10+ years securing cloud networks and zero-trust infrastructure. Open to mentoring students in network security and ethical hacking.",
    location: "Chennai",
    country: "India",
    phone: null,
    date_of_birth: "1994-09-15",
    created_at: "2025-04-10T10:00:00Z",
    updated_at: new Date().toISOString(),
    last_active_at: new Date().toISOString(),
    is_active: true,
    visibility: "public",
  },
];

export const SEED_EDUCATION: Database["public"]["Tables"]["education_records"]["Row"][] = [
  {
    id: "e1111111-1111-1111-1111-111111111111",
    user_id: DEMO_USER_ID,
    institution_id: "11111111-1111-1111-1111-111111111111",
    degree_id: "d1111111-1111-1111-1111-111111111111",
    field_of_study: "Electronics and Communication Engineering",
    start_year: 2022,
    end_year: 2026,
    graduation_year: null,
    expected_graduation_year: 2026,
    status: "current",
    description: "Undergraduate student focusing on microprocessors, computer networks, and programming.",
    created_at: "2026-01-10T10:00:00Z",
    updated_at: new Date().toISOString(),
  },
  {
    id: "e2222222-2222-2222-2222-222222222222",
    user_id: MENTOR_RAHUL_ID,
    institution_id: "11111111-1111-1111-1111-111111111111",
    degree_id: "d1111111-1111-1111-1111-111111111111",
    field_of_study: "Electronics and Communication Engineering",
    start_year: 2017,
    end_year: 2021,
    graduation_year: 2021,
    expected_graduation_year: null,
    status: "graduated",
    description: "Graduated with honors. Active lead of the college Open Source Society.",
    created_at: "2025-06-01T10:00:00Z",
    updated_at: new Date().toISOString(),
  },
  {
    id: "e2222223-2222-2222-2222-222222222222",
    user_id: MENTOR_RAHUL_ID,
    institution_id: "22222222-2222-2222-2222-222222222222",
    degree_id: "d3333333-3333-3333-3333-333333333333",
    field_of_study: "Cloud Computing & Distributed Systems",
    start_year: 2021,
    end_year: 2023,
    graduation_year: 2023,
    expected_graduation_year: null,
    status: "graduated",
    description: "Master's thesis on high-throughput distributed schedulers.",
    created_at: "2025-06-01T10:00:00Z",
    updated_at: new Date().toISOString(),
  },
  {
    id: "e3333333-3333-3333-3333-333333333333",
    user_id: MENTOR_ANANYA_ID,
    institution_id: "11111111-1111-1111-1111-111111111111",
    degree_id: "d1111111-1111-1111-1111-111111111111",
    field_of_study: "Electronics and Communication Engineering",
    start_year: 2016,
    end_year: 2020,
    graduation_year: 2020,
    expected_graduation_year: null,
    status: "graduated",
    description: "ECE to Software transition pathway lead.",
    created_at: "2025-05-12T10:00:00Z",
    updated_at: new Date().toISOString(),
  },
];

export const SEED_PROFILES: Database["public"]["Tables"]["professional_profiles"]["Row"][] = [
  {
    id: "p1111111-1111-1111-1111-111111111111",
    user_id: DEMO_USER_ID,
    current_company: null,
    current_role: "Student Researcher",
    industry: "Higher Education",
    years_of_experience: 0,
    linkedin_url: "https://linkedin.com/in/rohan-varma",
    portfolio_url: "https://rohanvarma.dev",
    github_url: "https://github.com/rohan-v",
    resume_url: null,
    open_to_work: true,
    open_to_mentor: false,
    open_to_hiring: false,
    open_to_referrals: false,
    created_at: "2026-01-10T10:00:00Z",
    updated_at: new Date().toISOString(),
  },
  {
    id: "p2222222-2222-2222-2222-222222222222",
    user_id: MENTOR_RAHUL_ID,
    current_company: "Amazon Web Services",
    current_role: "Senior Cloud Architect",
    industry: "Cloud Computing",
    years_of_experience: 5.5,
    linkedin_url: "https://linkedin.com/in/rahul-cloud",
    portfolio_url: null,
    github_url: "https://github.com/rahul-cloud",
    resume_url: null,
    open_to_work: false,
    open_to_mentor: true,
    open_to_hiring: true,
    open_to_referrals: true,
    created_at: "2025-06-01T10:00:00Z",
    updated_at: new Date().toISOString(),
  },
  {
    id: "p3333333-3333-3333-3333-333333333333",
    user_id: MENTOR_ANANYA_ID,
    current_company: "Microsoft",
    current_role: "Software Engineer II",
    industry: "Software Engineering",
    years_of_experience: 4.5,
    linkedin_url: "https://linkedin.com/in/ananya-dev",
    portfolio_url: null,
    github_url: "https://github.com/ananya-dev",
    resume_url: null,
    open_to_work: false,
    open_to_mentor: true,
    open_to_hiring: false,
    open_to_referrals: true,
    created_at: "2025-05-12T10:00:00Z",
    updated_at: new Date().toISOString(),
  },
  {
    id: "p4444444-4444-4444-4444-444444444444",
    user_id: MENTOR_PRIYA_ID,
    current_company: "Google",
    current_role: "Site Reliability Engineer",
    industry: "Cloud Infrastructure",
    years_of_experience: 3.0,
    linkedin_url: "https://linkedin.com/in/priya-sre",
    portfolio_url: null,
    github_url: "https://github.com/priya-sre",
    resume_url: null,
    open_to_work: false,
    open_to_mentor: true,
    open_to_hiring: true,
    open_to_referrals: true,
    created_at: "2025-07-20T10:00:00Z",
    updated_at: new Date().toISOString(),
  },
  {
    id: "p5555555-5555-5555-5555-555555555555",
    user_id: MENTOR_VIKRAM_ID,
    current_company: "Cisco Systems",
    current_role: "Cybersecurity Lead",
    industry: "Cybersecurity",
    years_of_experience: 6.0,
    linkedin_url: "https://linkedin.com/in/vikram-sec",
    portfolio_url: null,
    github_url: null,
    resume_url: null,
    open_to_work: false,
    open_to_mentor: true,
    open_to_hiring: false,
    open_to_referrals: false,
    created_at: "2025-04-10T10:00:00Z",
    updated_at: new Date().toISOString(),
  },
];

export const SEED_SKILLS: Database["public"]["Tables"]["skills"]["Row"][] = [
  { id: "s1", name: "Python", category: "Programming", description: "Backend & scripting", created_at: new Date().toISOString() },
  { id: "s2", name: "Java", category: "Programming", description: "Enterprise backend", created_at: new Date().toISOString() },
  { id: "s3", name: "SQL", category: "Databases", description: "Relational database querying", created_at: new Date().toISOString() },
  { id: "s4", name: "Linux", category: "Operating Systems", description: "Server administration", created_at: new Date().toISOString() },
  { id: "s5", name: "IoT & Embedded", category: "Hardware", description: "Microcontrollers and sensors", created_at: new Date().toISOString() },
  { id: "s6", name: "AWS", category: "Cloud Computing", description: "Amazon Web Services", created_at: new Date().toISOString() },
  { id: "s7", name: "Docker", category: "DevOps", description: "Containerization", created_at: new Date().toISOString() },
  { id: "s8", name: "Kubernetes", category: "DevOps", description: "Container orchestration", created_at: new Date().toISOString() },
  { id: "s9", name: "CI/CD", category: "DevOps", description: "Automated pipelines", created_at: new Date().toISOString() },
  { id: "s10", name: "Terraform", category: "DevOps", description: "Infrastructure as Code", created_at: new Date().toISOString() },
  { id: "s11", name: "Spring Boot", category: "Backend", description: "Java web microservices", created_at: new Date().toISOString() },
  { id: "s12", name: "Azure", category: "Cloud Computing", description: "Microsoft Cloud", created_at: new Date().toISOString() },
  { id: "s13", name: "Cybersecurity", category: "Security", description: "Threat defense", created_at: new Date().toISOString() },
];

export const SEED_USER_SKILLS: (Database["public"]["Tables"]["user_skills"]["Row"] & { skill?: Database["public"]["Tables"]["skills"]["Row"] })[] = [
  // Rohan's existing skills
  { id: "us1", user_id: DEMO_USER_ID, skill_id: "s1", proficiency_level: "intermediate", years_experience: 2, source: "self_reported", verified: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString(), skill: { id: "s1", name: "Python", category: "Programming", description: "Backend & scripting", created_at: "" } },
  { id: "us2", user_id: DEMO_USER_ID, skill_id: "s2", proficiency_level: "intermediate", years_experience: 2, source: "self_reported", verified: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString(), skill: { id: "s2", name: "Java", category: "Programming", description: "Enterprise backend", created_at: "" } },
  { id: "us3", user_id: DEMO_USER_ID, skill_id: "s3", proficiency_level: "intermediate", years_experience: 1.5, source: "self_reported", verified: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString(), skill: { id: "s3", name: "SQL", category: "Databases", description: "Relational database querying", created_at: "" } },
  { id: "us4", user_id: DEMO_USER_ID, skill_id: "s4", proficiency_level: "intermediate", years_experience: 2, source: "self_reported", verified: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString(), skill: { id: "s4", name: "Linux", category: "Operating Systems", description: "Server administration", created_at: "" } },
  { id: "us5", user_id: DEMO_USER_ID, skill_id: "s5", proficiency_level: "advanced", years_experience: 3, source: "project", verified: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString(), skill: { id: "s5", name: "IoT & Embedded", category: "Hardware", description: "Microcontrollers and sensors", created_at: "" } },

  // Rahul Sharma's skills (possesses the missing cloud skills)
  { id: "us6", user_id: MENTOR_RAHUL_ID, skill_id: "s6", proficiency_level: "expert", years_experience: 5.5, source: "experience", verified: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString(), skill: { id: "s6", name: "AWS", category: "Cloud Computing", description: "Amazon Web Services", created_at: "" } },
  { id: "us7", user_id: MENTOR_RAHUL_ID, skill_id: "s7", proficiency_level: "expert", years_experience: 5.0, source: "experience", verified: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString(), skill: { id: "s7", name: "Docker", category: "DevOps", description: "Containerization", created_at: "" } },
  { id: "us8", user_id: MENTOR_RAHUL_ID, skill_id: "s8", proficiency_level: "expert", years_experience: 4.5, source: "experience", verified: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString(), skill: { id: "s8", name: "Kubernetes", category: "DevOps", description: "Container orchestration", created_at: "" } },
  { id: "us9", user_id: MENTOR_RAHUL_ID, skill_id: "s9", proficiency_level: "advanced", years_experience: 4.0, source: "experience", verified: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString(), skill: { id: "s9", name: "CI/CD", category: "DevOps", description: "Automated pipelines", created_at: "" } },
  { id: "us10", user_id: MENTOR_RAHUL_ID, skill_id: "s10", proficiency_level: "expert", years_experience: 4.0, source: "experience", verified: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString(), skill: { id: "s10", name: "Terraform", category: "DevOps", description: "Infrastructure as Code", created_at: "" } },
];

export const SEED_CAREER_GOALS: Database["public"]["Tables"]["career_goals"]["Row"][] = [
  {
    id: "cg1",
    user_id: DEMO_USER_ID,
    goal_text: "I want to become a Cloud Engineer.",
    target_role: "Cloud Engineer",
    target_industry: "Cloud Computing & DevOps",
    target_company: "Amazon Web Services, Microsoft, Google",
    target_location: "Bangalore / Remote",
    target_timeframe: "Next 6 Months",
    priority: 1,
    status: "active",
    created_at: "2026-01-15T10:00:00Z",
    updated_at: new Date().toISOString(),
  },
];

export const SEED_CAREER_ANALYSIS: Database["public"]["Tables"]["career_analyses"]["Row"] = {
  id: "ca1",
  user_id: DEMO_USER_ID,
  career_goal_id: "cg1",
  current_profile_summary: "Strong programming fundamentals in Python and Java with hands-on Linux and embedded networking experience from an ECE background.",
  target_role_summary: "Cloud Engineers build and maintain resilient cloud infrastructure, automate deployment pipelines, and configure containerized workloads.",
  strengths: ["Linux Operating System", "Python & Java Automation", "Computer Networking Fundamentals", "SQL Database Basics"],
  skill_gaps: [
    { skill: "AWS", importance: "critical", reason: "Foundational public cloud platform required for compute, VPC, and storage management." },
    { skill: "Docker", importance: "critical", reason: "Essential for packaging services into predictable, containerized units." },
    { skill: "Kubernetes", importance: "important", reason: "Standard orchestration layer for managing distributed enterprise container clusters." },
    { skill: "CI/CD", importance: "important", reason: "Automated test-and-deploy pipelines required for professional production deployments." },
  ],
  recommended_skills: ["AWS Solutions Architect Associate", "Docker Microservices", "Kubernetes (EKS)", "GitHub Actions CI/CD"],
  recommended_projects: [
    "Deploy a multi-tier containerized web application on AWS with Docker",
    "Automate Kubernetes zero-downtime rolling updates using CI/CD",
  ],
  recommended_certifications: ["AWS Certified Solutions Architect - Associate", "Docker Certified Associate (DCA)"],
  recommended_roles: ["Cloud Infrastructure Engineer", "Junior DevOps Engineer", "Associate Cloud Consultant"],
  career_readiness_score: 68,
  analysis_version: "v1.0",
  created_at: "2026-01-15T10:05:00Z",
  updated_at: new Date().toISOString(),
};

export const SEED_SKILL_GAPS: (Database["public"]["Tables"]["skill_gaps"]["Row"] & { skill?: Database["public"]["Tables"]["skills"]["Row"] })[] = [
  {
    id: "sg1",
    user_id: DEMO_USER_ID,
    career_goal_id: "cg1",
    skill_id: "s6",
    importance: "critical",
    current_level: "none",
    required_level: "intermediate",
    gap_score: 0.85,
    reason: "Foundational public cloud provider required for provisioning compute, VPCs, and storage.",
    status: "identified",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    skill: { id: "s6", name: "AWS", category: "Cloud Computing", description: "Amazon Web Services", created_at: "" },
  },
  {
    id: "sg2",
    user_id: DEMO_USER_ID,
    career_goal_id: "cg1",
    skill_id: "s7",
    importance: "critical",
    current_level: "none",
    required_level: "intermediate",
    gap_score: 0.80,
    reason: "Essential containerization standard required by all modern cloud teams.",
    status: "identified",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    skill: { id: "s7", name: "Docker", category: "DevOps", description: "Containerization", created_at: "" },
  },
  {
    id: "sg3",
    user_id: DEMO_USER_ID,
    career_goal_id: "cg1",
    skill_id: "s8",
    importance: "important",
    current_level: "none",
    required_level: "intermediate",
    gap_score: 0.75,
    reason: "Container orchestration platform for scaling distributed cloud workloads.",
    status: "identified",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    skill: { id: "s8", name: "Kubernetes", category: "DevOps", description: "Container orchestration", created_at: "" },
  },
  {
    id: "sg4",
    user_id: DEMO_USER_ID,
    career_goal_id: "cg1",
    skill_id: "s9",
    importance: "important",
    current_level: "none",
    required_level: "intermediate",
    gap_score: 0.70,
    reason: "Automated continuous delivery pipelines for production release management.",
    status: "identified",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    skill: { id: "s9", name: "CI/CD", category: "DevOps", description: "Automated pipelines", created_at: "" },
  },
];

export const SEED_ROADMAPS: Database["public"]["Tables"]["career_roadmaps"]["Row"][] = [
  {
    id: "rm1",
    user_id: DEMO_USER_ID,
    career_goal_id: "cg1",
    title: "Cloud Engineering Acceleration Roadmap",
    description: "Tailored 4-phase progression moving from hardware/Linux fundamentals into AWS cloud architecture, containerization, and alumni mentorship.",
    duration_estimate: "6 Months",
    status: "in_progress",
    created_at: "2026-01-15T10:10:00Z",
    updated_at: new Date().toISOString(),
  },
];

export const SEED_ROADMAP_ITEMS: Database["public"]["Tables"]["roadmap_items"]["Row"][] = [
  {
    id: "rmi1",
    roadmap_id: "rm1",
    title: "Linux Server Administration & TCP/IP Protocols",
    description: "Master terminal utilities, file permissions, systemd services, SSH tunneling, and networking configuration.",
    item_type: "learn_skill",
    skill_id: "s4",
    sequence_order: 1,
    estimated_duration: "3 Weeks",
    resource_url: "https://linuxjourney.com",
    status: "completed",
    completed_at: "2026-01-28T10:00:00Z",
    created_at: "2026-01-15T10:10:00Z",
    updated_at: new Date().toISOString(),
  },
  {
    id: "rmi2",
    roadmap_id: "rm1",
    title: "AWS Core Cloud Infrastructure (EC2, VPC, S3, IAM)",
    description: "Provision virtual networks, configure security groups, create elastic compute nodes, and configure IAM role privileges.",
    item_type: "learn_skill",
    skill_id: "s6",
    sequence_order: 2,
    estimated_duration: "4 Weeks",
    resource_url: "https://aws.amazon.com/training",
    status: "in_progress",
    completed_at: null,
    created_at: "2026-01-15T10:10:00Z",
    updated_at: new Date().toISOString(),
  },
  {
    id: "rmi3",
    roadmap_id: "rm1",
    title: "Docker Microservice Packaging Project",
    description: "Containerize Python/Java backend services using multi-stage Dockerfiles and publish to Docker Hub / Amazon ECR.",
    item_type: "project",
    skill_id: "s7",
    sequence_order: 3,
    estimated_duration: "3 Weeks",
    resource_url: "https://docs.docker.com/get-started",
    status: "not_started",
    completed_at: null,
    created_at: "2026-01-15T10:10:00Z",
    updated_at: new Date().toISOString(),
  },
  {
    id: "rmi4",
    roadmap_id: "rm1",
    title: "Kubernetes Cluster Deployment & GitHub Actions CI/CD",
    description: "Deploy containerized applications to AWS EKS with automated zero-downtime rolling updates via GitHub Actions.",
    item_type: "project",
    skill_id: "s8",
    sequence_order: 4,
    estimated_duration: "4 Weeks",
    resource_url: "https://kubernetes.io/docs/tutorials",
    status: "not_started",
    completed_at: null,
    created_at: "2026-01-15T10:10:00Z",
    updated_at: new Date().toISOString(),
  },
  {
    id: "rmi5",
    roadmap_id: "rm1",
    title: "Connect with Alumnus Mentor Rahul Sharma for Project Review",
    description: "Review multi-region container deployment architecture with senior mentor to prepare for entry-level interviews.",
    item_type: "mentor",
    skill_id: null,
    sequence_order: 5,
    estimated_duration: "1 Week",
    resource_url: null,
    status: "not_started",
    completed_at: null,
    created_at: "2026-01-15T10:10:00Z",
    updated_at: new Date().toISOString(),
  },
];

export const SEED_MATCH_RESULTS: (Database["public"]["Tables"]["match_results"]["Row"] & {
  matched_user?: Database["public"]["Tables"]["users"]["Row"] & {
    profile?: Database["public"]["Tables"]["professional_profiles"]["Row"];
    education?: Database["public"]["Tables"]["education_records"]["Row"][];
  };
})[] = [
  {
    id: "mr1",
    user_id: DEMO_USER_ID,
    matched_user_id: MENTOR_RAHUL_ID,
    career_goal_id: "cg1",
    match_type: "alumni_mentor",
    overall_score: 94.0,
    career_goal_score: 30.0, // 30/30 (Exact Cloud Architect)
    skill_score: 23.5,       // 23.5/25 (AWS, Docker, K8s expert)
    education_score: 20.0,   // 20/20 (ABC College ECE Alum)
    industry_score: 14.0,    // 14/15 (AWS Cloud Computing)
    experience_score: 6.5,   // 6.5/10 (5.5 years experience)
    location_score: 8.5,
    explanation: "Rahul Sharma graduated from your exact college in ECE and successfully transitioned to Senior Cloud Architect at AWS. He directly works with your missing skills (AWS, Docker, Kubernetes) and actively mentors students.",
    match_reasons: [
      "Alumni of your college (ABC College of Engineering)",
      "Navigated the same ECE to Cloud career transition",
      "Possesses your 4 critical missing skills (AWS, Docker, Kubernetes, CI/CD)",
      "Senior Cloud Architect at Amazon Web Services",
      "Verified mentor with open availability for chat guidance",
    ],
    search_scope: "institution",
    created_at: new Date().toISOString(),
    expires_at: null,
    matched_user: {
      ...SEED_USERS.find((u) => u.id === MENTOR_RAHUL_ID)!,
      profile: SEED_PROFILES.find((p) => p.user_id === MENTOR_RAHUL_ID)!,
      education: SEED_EDUCATION.filter((e) => e.user_id === MENTOR_RAHUL_ID),
    },
  },
  {
    id: "mr2",
    user_id: DEMO_USER_ID,
    matched_user_id: MENTOR_PRIYA_ID,
    career_goal_id: "cg1",
    match_type: "alumni_mentor",
    overall_score: 87.0,
    career_goal_score: 28.0,
    skill_score: 23.0,
    education_score: 14.0, // Broader network (XYZ Tech)
    industry_score: 14.0,
    experience_score: 8.0,
    location_score: 8.0,
    explanation: "Priya Nair is a Site Reliability Engineer at Google with deep Kubernetes and CI/CD expertise. While from the broader university network, her infrastructure skill profile strongly aligns with your roadmap.",
    match_reasons: [
      "Site Reliability Engineer at Google",
      "Expert in Kubernetes clusters & automated CI/CD",
      "Broader regional network (XYZ Tech)",
      "Active mentor in cloud-native platforms",
    ],
    search_scope: "broader_alumni",
    created_at: new Date().toISOString(),
    expires_at: null,
    matched_user: {
      ...SEED_USERS.find((u) => u.id === MENTOR_PRIYA_ID)!,
      profile: SEED_PROFILES.find((p) => p.user_id === MENTOR_PRIYA_ID)!,
      education: SEED_EDUCATION.filter((e) => e.user_id === MENTOR_PRIYA_ID),
    },
  },
  {
    id: "mr3",
    user_id: DEMO_USER_ID,
    matched_user_id: MENTOR_ANANYA_ID,
    career_goal_id: "cg1",
    match_type: "alumni_mentor",
    overall_score: 84.5,
    career_goal_score: 24.0,
    skill_score: 18.0,
    education_score: 20.0, // Same college
    industry_score: 13.0,
    experience_score: 9.5,
    location_score: 7.0,
    explanation: "Ananya Patel transitioned from ECE at ABC College into backend distributed systems at Microsoft. She provides exceptional guidance on general software engineering transitions and enterprise APIs.",
    match_reasons: [
      "Alumna of your college (ABC College)",
      "Experienced ECE to software transition mentor",
      "Software Engineer II at Microsoft",
      "Strong Java, SQL, and Azure background",
    ],
    search_scope: "institution",
    created_at: new Date().toISOString(),
    expires_at: null,
    matched_user: {
      ...SEED_USERS.find((u) => u.id === MENTOR_ANANYA_ID)!,
      profile: SEED_PROFILES.find((p) => p.user_id === MENTOR_ANANYA_ID)!,
      education: SEED_EDUCATION.filter((e) => e.user_id === MENTOR_ANANYA_ID),
    },
  },
  {
    id: "mr4",
    user_id: DEMO_USER_ID,
    matched_user_id: MENTOR_VIKRAM_ID,
    career_goal_id: "cg1",
    match_type: "alumni_mentor",
    overall_score: 79.0,
    career_goal_score: 22.0,
    skill_score: 20.0,
    education_score: 12.0, // GIST alum
    industry_score: 14.0,
    experience_score: 11.0,
    location_score: 7.0,
    explanation: "Vikram Rao has 8+ years experience scaling infrastructure at Razorpay. Strong Terraform and Docker mentor, providing deep industry perspective on production stability.",
    match_reasons: [
      "Staff DevOps Engineer at Razorpay",
      "Expert in Infrastructure-as-Code & Docker pipelines",
      "National tech ecosystem network (GIST alum)",
      "Passionate open-source mentor",
    ],
    search_scope: "broader_alumni",
    created_at: new Date().toISOString(),
    expires_at: null,
    matched_user: {
      ...SEED_USERS.find((u) => u.id === MENTOR_VIKRAM_ID)!,
      profile: SEED_PROFILES.find((p) => p.user_id === MENTOR_VIKRAM_ID)!,
      education: SEED_EDUCATION.filter((e) => e.user_id === MENTOR_VIKRAM_ID),
    },
  },
];

export const SEED_CONNECTIONS: (Database["public"]["Tables"]["connections"]["Row"] & {
  partner?: Database["public"]["Tables"]["users"]["Row"];
})[] = [
  {
    id: "c1",
    requester_id: DEMO_USER_ID,
    receiver_id: MENTOR_RAHUL_ID,
    status: "accepted",
    connection_type: "mentor",
    source: "ai_recommendation",
    initial_message: "Hi Rahul, I noticed that you transitioned from an ECE background at ABC College into cloud engineering and now work with AWS and Kubernetes. I am currently working toward an entry-level Cloud Engineer role and would really value your advice.",
    created_at: "2026-01-20T14:30:00Z",
    updated_at: new Date().toISOString(),
    accepted_at: "2026-01-20T16:00:00Z",
    partner: SEED_USERS.find((u) => u.id === MENTOR_RAHUL_ID)!,
  },
  {
    id: "c2",
    requester_id: DEMO_USER_ID,
    receiver_id: MENTOR_PRIYA_ID,
    status: "pending",
    connection_type: "mentor",
    source: "ai_recommendation",
    initial_message: "Hello Priya, I came across your SRE journey at Google and noticed your deep focus on Kubernetes clusters. I'd love to learn from your career path.",
    created_at: "2026-01-22T09:15:00Z",
    updated_at: new Date().toISOString(),
    accepted_at: null,
    partner: SEED_USERS.find((u) => u.id === MENTOR_PRIYA_ID)!,
  },
];

export const SEED_CONVERSATIONS = [
  {
    id: "conv1",
    created_at: "2026-01-20T16:00:00Z",
    updated_at: new Date().toISOString(),
    last_message_at: "2026-01-20T17:15:00Z",
    partner: SEED_USERS.find((u) => u.id === MENTOR_RAHUL_ID)!,
    messages: [
      {
        id: "m1",
        conversation_id: "conv1",
        sender_id: DEMO_USER_ID,
        message_text: "Hi Rahul! Thanks so much for connecting. I am in my final year of ECE at ABC College and aiming for an entry-level Cloud Engineer role. Any tips on bridging from hardware/electronics to cloud?",
        message_type: "text" as const,
        created_at: "2026-01-20T16:10:00Z",
        edited_at: null,
        deleted_at: null,
      },
      {
        id: "m2",
        conversation_id: "conv1",
        sender_id: MENTOR_RAHUL_ID,
        message_text: "Hey Rohan, great to meet a junior from ABC! Don't worry about the ECE background—your Linux and Python foundation will actually give you an edge over generic applicants. My advice: learn AWS core fundamentals first, containerize a real app with Docker, and deploy an automated cloud project before applying.",
        message_type: "text" as const,
        created_at: "2026-01-20T16:45:00Z",
        edited_at: null,
        deleted_at: null,
      },
      {
        id: "m3",
        conversation_id: "conv1",
        sender_id: DEMO_USER_ID,
        message_text: "That gives me a lot of confidence! I already have Linux and Python down from an IoT project. I will dive right into AWS compute and Docker packaging.",
        message_type: "text" as const,
        created_at: "2026-01-20T17:00:00Z",
        edited_at: null,
        deleted_at: null,
      },
      {
        id: "m4",
        conversation_id: "conv1",
        sender_id: MENTOR_RAHUL_ID,
        message_text: "Awesome. Once you have a working Dockerized deployment on AWS, ping me and I'll do a mock design review of your architecture.",
        message_type: "text" as const,
        created_at: "2026-01-20T17:15:00Z",
        edited_at: null,
        deleted_at: null,
      },
    ],
  },
];

export const SEED_OPPORTUNITIES: (Database["public"]["Tables"]["opportunities"]["Row"] & {
  skills?: Database["public"]["Tables"]["skills"]["Row"][];
})[] = [
  {
    id: "op1",
    posted_by_user_id: MENTOR_RAHUL_ID,
    company_name: "CloudScale Systems",
    title: "Cloud & DevOps Engineering Intern",
    description: "Fast-growing cloud infrastructure firm seeking entry-level interns to build Terraform modules, manage Docker container deployments on AWS, and configure monitoring alarms.",
    opportunity_type: "internship",
    location: "Bangalore",
    work_mode: "hybrid",
    application_url: "https://cloudscale.careers/intern-cloud",
    deadline: "2026-04-30",
    is_active: true,
    created_at: "2026-01-18T10:00:00Z",
    updated_at: new Date().toISOString(),
    skills: [
      { id: "s6", name: "AWS", category: "Cloud", description: "", created_at: "" },
      { id: "s7", name: "Docker", category: "DevOps", description: "", created_at: "" },
      { id: "s4", name: "Linux", category: "OS", description: "", created_at: "" },
    ],
  },
  {
    id: "op2",
    posted_by_user_id: MENTOR_ANANYA_ID,
    company_name: "FinTech Distributed Systems",
    title: "Junior Cloud Infrastructure Associate",
    description: "Manage container clusters, assist with CI/CD deployment pipelines, and maintain high-uptime cloud operations for financial platforms.",
    opportunity_type: "job",
    location: "Chennai",
    work_mode: "remote",
    application_url: "https://fintech.careers/jr-cloud",
    deadline: "2026-05-15",
    is_active: true,
    created_at: "2026-01-22T10:00:00Z",
    updated_at: new Date().toISOString(),
    skills: [
      { id: "s6", name: "AWS", category: "Cloud", description: "", created_at: "" },
      { id: "s8", name: "Kubernetes", category: "DevOps", description: "", created_at: "" },
      { id: "s9", name: "CI/CD", category: "DevOps", description: "", created_at: "" },
    ],
  },
  {
    id: "op3",
    posted_by_user_id: MENTOR_VIKRAM_ID,
    company_name: "InfraCloud Networks",
    title: "Associate DevOps / SRE Engineer",
    description: "Work on container orchestrators, infrastructure automation with Terraform, and telemetry monitoring pipelines for global microservices.",
    opportunity_type: "job",
    location: "Hyderabad",
    work_mode: "hybrid",
    application_url: "https://infracloud.careers/associate-devops",
    deadline: "2026-06-01",
    is_active: true,
    created_at: "2026-01-24T14:00:00Z",
    updated_at: new Date().toISOString(),
    skills: [
      { id: "s7", name: "Docker", category: "DevOps", description: "", created_at: "" },
      { id: "s8", name: "Kubernetes", category: "DevOps", description: "", created_at: "" },
      { id: "s4", name: "Linux", category: "OS", description: "", created_at: "" },
    ],
  },
];

export const SEED_POSTS: (Database["public"]["Tables"]["posts"]["Row"] & {
  author?: Database["public"]["Tables"]["users"]["Row"];
  likes_count?: number;
  comments_count?: number;
})[] = [
  {
    id: "post1",
    user_id: DEMO_USER_ID,
    content: "Excited to share that I just completed building my IoT Smart Environmental Monitor! Developed with ESP32 microcontrollers, Python telemetry streaming, and MQTT message brokers. Now diving into AWS IoT Core and containerized cloud deployments!",
    media_url: null,
    post_type: "project",
    visibility: "public",
    created_at: "2026-01-25T11:00:00Z",
    updated_at: new Date().toISOString(),
    author: SEED_USERS.find((u) => u.id === DEMO_USER_ID),
    likes_count: 14,
    comments_count: 3,
  },
  {
    id: "post2",
    user_id: MENTOR_RAHUL_ID,
    content: "To all the students transitioning from non-CS disciplines (ECE, Mechanical, Electrical) into Cloud & DevOps: your fundamentals in systems and problem solving are a superpower. Don't memorize 50 tools—master Linux, Docker, and one cloud provider deeply.",
    media_url: null,
    post_type: "career_update",
    visibility: "public",
    created_at: "2026-01-26T09:30:00Z",
    updated_at: new Date().toISOString(),
    author: SEED_USERS.find((u) => u.id === MENTOR_RAHUL_ID),
    likes_count: 42,
    comments_count: 8,
  },
  {
    id: "post3",
    user_id: MENTOR_ANANYA_ID,
    content: "Thrilled to share that our distributed backend infrastructure team at Microsoft just rolled out multi-region active-active clusters with zero downtime! Grateful for the foundational mentorship I received during my college days at ABC College.",
    media_url: null,
    post_type: "career_update",
    visibility: "public",
    created_at: "2026-01-27T15:00:00Z",
    updated_at: new Date().toISOString(),
    author: SEED_USERS.find((u) => u.id === MENTOR_ANANYA_ID),
    likes_count: 38,
    comments_count: 5,
  },
  {
    id: "post4",
    user_id: MENTOR_PRIYA_ID,
    content: "Our Site Reliability Engineering org at Google is looking for passionate cloud enthusiasts interested in large-scale Kubernetes orchestration. Reach out if you're exploring the SRE space or have questions on production debugging!",
    media_url: null,
    post_type: "general",
    visibility: "public",
    created_at: "2026-01-28T08:20:00Z",
    updated_at: new Date().toISOString(),
    author: SEED_USERS.find((u) => u.id === MENTOR_PRIYA_ID),
    likes_count: 56,
    comments_count: 12,
  },
];

export const SEED_AGENT_SESSION: Database["public"]["Tables"]["agent_sessions"]["Row"] & {
  actions: Database["public"]["Tables"]["agent_actions"]["Row"][];
} = {
  id: "as1",
  user_id: DEMO_USER_ID,
  agent_type: "networking_agent",
  goal: "Find cloud engineering mentors from my institution who can help with AWS and Docker",
  status: "completed",
  context: {
    target_role: "Cloud Engineer",
    search_scope: "institution",
    retrieved_candidates: 12,
    top_candidate: "Rahul Sharma",
    score: 94.0,
  },
  started_at: "2026-01-20T14:28:00Z",
  completed_at: "2026-01-20T14:30:00Z",
  actions: [
    {
      id: "act1",
      session_id: "as1",
      action_type: "analyze_career_goal",
      target_entity_type: "career_goal",
      target_entity_id: "cg1",
      input_data: { goal: "I want to become a Cloud Engineer" },
      output_data: { target_role: "Cloud Engineer", required_skills: ["AWS", "Docker", "Kubernetes", "CI/CD"] },
      status: "completed",
      requires_approval: false,
      approved_at: null,
      created_at: "2026-01-20T14:28:10Z",
    },
    {
      id: "act2",
      session_id: "as1",
      action_type: "search_alumni_network",
      target_entity_type: "institution",
      target_entity_id: "11111111-1111-1111-1111-111111111111",
      input_data: { institution: "ABC College of Engineering", role: "Cloud Engineer", skills: ["AWS", "Docker"] },
      output_data: { candidate_count: 12, top_match: "Rahul Sharma" },
      status: "completed",
      requires_approval: false,
      approved_at: null,
      created_at: "2026-01-20T14:28:30Z",
    },
    {
      id: "act3",
      session_id: "as1",
      action_type: "calculate_deterministic_match",
      target_entity_type: "user",
      target_entity_id: MENTOR_RAHUL_ID,
      input_data: { student_id: DEMO_USER_ID, candidate_id: MENTOR_RAHUL_ID },
      output_data: {
        score: 94.0,
        breakdown: { goal_similarity: 30, skill_similarity: 23.5, education_connection: 20, industry_relevance: 14, experience: 6.5 },
      },
      status: "completed",
      requires_approval: false,
      approved_at: null,
      created_at: "2026-01-20T14:28:50Z",
    },
    {
      id: "act4",
      session_id: "as1",
      action_type: "generate_personalized_message",
      target_entity_type: "connection",
      target_entity_id: null,
      input_data: { recipient: "Rahul Sharma", shared_journey: "ABC College ECE transition" },
      output_data: {
        message: "Hi Rahul, I noticed that you transitioned from an ECE background at ABC College into cloud engineering and now work with AWS and Kubernetes. I am currently working toward an entry-level Cloud Engineer role and would really value your advice on what to prioritize.",
      },
      status: "completed",
      requires_approval: true,
      approved_at: "2026-01-20T14:29:55Z",
      created_at: "2026-01-20T14:29:10Z",
    },
  ],
};
